apiVersion: v2
name: k8s-health-report
description: "Weekly Kubernetes cluster health report"
type: application
version: 1.0.0
appVersion: "1.0"

keywords:
  - automation
  - cronjob
  - observability
  - monitoring

home: https://github.com/rprakashdass/homelab-gitops
sources:
  - https://github.com/rprakashdass/homelab-gitops

maintainers:
  - name: rprakashdass
    email: rprakashdass@gmail.com

dependencies:
  - name: base-chart
    version: "1.0.0"
    repository: "file://../../platform/base-chart"
