apiVersion: v2
name: minio
description: "MinIO S3-compatible object storage"
type: application
version: 1.0.0
appVersion: "latest"

keywords:
  - storage
  - minio
  - s3
  - object-storage

home: https://github.com/rprakashdass/homelab-gitops
sources:
  - https://github.com/rprakashdass/homelab-gitops

maintainers:
  - name: rprakashdass
    email: rprakashdass@gmail.com

dependencies:
  - name: base-chart
    version: "1.0.0"
    repository: "file://../../platform/base-chart"
