{{- $gitRepo := "https://github.com/rprakashdass/homelab-gitops.git" }}
{{- $gitBranch := "main" }}
{{- $argocdNamespace := "argocd" }}
{{- $defaultDeployNamespace := "home" }}
{{- $project := "home" }}

{{- range $name, $app := .Values.applications }}
{{- if $app.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-{{ $name }}
  namespace: {{ $argocdNamespace }}
  labels:
    app.kubernetes.io/name: home-{{ $name }}
    app.kubernetes.io/component: argocd-application
    app.kubernetes.io/part-of: home-automation-platform
  annotations:
    app.kubernetes.io/description: {{ $app.description | quote }}
    argocd.argoproj.io/sync-wave: {{ $app.syncWave | quote }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $project }}

{{- if $app.useExternalChart }}
  sources:
    - repoURL: {{ $app.externalChart.repoURL }}
      chart: {{ $app.externalChart.chart }}
      targetRevision: {{ $app.externalChart.targetRevision }}
      helm:
        releaseName: {{ $name }}
        valueFiles:
          - $values/{{ $app.externalChart.valueFile }}
    - repoURL: {{ $gitRepo }}
      targetRevision: {{ $gitBranch }}
      ref: values
{{- else }}
  source:
    repoURL: {{ $gitRepo }}
    targetRevision: {{ $gitBranch }}
    path: {{ $app.path }}
{{- end }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $app.namespace | default $defaultDeployNamespace }}

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

---
{{- end }}
{{- end }}
