apiVersion: v1
kind: Secret
metadata:
  name: telegram-bot-secrets
  namespace: home
type: Opaque
data:
  TELEGRAM_BOT_TOKEN: ODQzMjEwMzQ5MDpBQUZvMEdJQUJzVjBSNnFtZnlVbmpBaXAtcUJ0Q0lTNVJnOA==
  TELEGRAM_CHAT_ID: ODc0MzQyNzY1Mg==
