apiVersion: ENC[AES256_GCM,data:s24=,iv:LXlLq0m5wzSdO9QHr1EmIkpvz3NphKTSUDmbDFRhU/M=,tag:lh5WbwTgHq6HRXTi0hApDA==,type:str]
kind: ENC[AES256_GCM,data:CRFDbDWX,iv:/z4mR7jnuN4BtH6ceBAZWwuObJkvnbR8WdLV2KeBonA=,tag:r//DPTBMwA8bp0DaaRQB1w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vTjwqGwio5i7nWj7W6mhAJHnlhg=,iv:+6zmrxHl33QBzfVvP5P6vUq0esUFo4CyghMNvr+jyIQ=,tag:dA1031BtFwmi+UMeQ/57iw==,type:str]
type: ENC[AES256_GCM,data:2JAhX2gY,iv:KLA3GXv2Tp4ZGOoN7fb92Bww/GvCFtpMXp0wjjQAIeg=,tag:h4Ya0HibBsqAyjWvvpgovg==,type:str]
data:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:RJhQxnOJjBE3JdDCV+UknTKiBmYUfnQDs/kCcrZ5YFkB74AH/FSDLTSKYtPNqA==,iv:4Thtvv9/1HQ0U6uHUpdAODAN+oQpKef0EFCXyIu3nAU=,tag:e4vQxRAvOnW+Ia/J5qCdoA==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:5NFOhBaBCykyuQ==,iv:RwYiWspovBai48CoGConUJ9YhIyJSTQ0KQbRKe3V30Q=,tag:KyFcb19IZYs1GDQzo3fNaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcnpiQ3ozMWU5UFJZQWJO
            WS9YWjY3bmpPdTh2b1pjam1sOG5EYUNJSEYwClJnd2EzR0h2V1U5TzdnMjh5Nlcx
            aU1qejFZLzNLbFhpNEk5ZGlycUhrdjgKLS0tIDBFNkZCc2FTSm9KZzlFZXppRWJS
            dXdoNStpYjBTbjNheUlGVnNUVXNXcUUKddKcwzhNuP1P4mf5z2Ws0hbJxyJ+Vm6E
            i6/t2iKIH5vXY/ugKPrrasqTBgt+AVK5T8gW+uU62dt+sFFxuINbjQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p4u42ltpqj0jxpuhx47pm0dhpmuqw2x8utyrxsr6xrgnzx0slq7q9u5jcw
    lastmodified: "2026-06-13T13:43:13Z"
    mac: ENC[AES256_GCM,data:6CYm6jpksr51JrcEFmkEpqUPn0E4TpHHW0ZKHQ3F9WHB/8IuKv2EsgjeijjCNqVrgQSeicuuUJmiMSxs+jcgzv/TYW5NS5mjFCKiL7YVSsQgkMOLcsEu0dahp+1LD2uTyyaJnnW4lttStbBUUKhcpfeMjyjAOAAgFZKIomoJ0hc=,iv:uFQQDySWLEjCJw+NIKvAM1nfdDAjacTHFdAfRM1vxPQ=,tag:keW97Yx85lJDstVNsiL7fQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
