apiVersion: ENC[AES256_GCM,data:CeA=,iv:+VJDT9KarUb2uHBEkIMP+c4fr2ecOE7V1mABzHkdYYo=,tag:4eHAliYz9cN0dwgx3sDRSg==,type:str]
kind: ENC[AES256_GCM,data:kRBBFI2m,iv:JjWwB9ghNt2BtI2WjQEx6Rwhk2rEZVr7u8O+k4BeFNE=,tag:jh9OoF+0xxMyRTDl7lPh/A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:DBqQwahHupbJ3TyueJm7vQGHbxM=,iv:F8+DSpGyo/31pQpdZ23+WkIu3PXhflmMQ60cKhGZCmA=,tag:JdFpuHST+phtD/by1MM1zg==,type:str]
type: ENC[AES256_GCM,data:hnnJaizZ,iv:beumzKKHgLDQO1plybneknBwUQA2QmZqFRr2B7K/Aps=,tag:kli7U8bJ2Nl5gDC8WpkukQ==,type:str]
data:
    TELEGRAM_BOT_TOKEN: ENC[AES256_GCM,data:jGrgHa0F998EVx5f7U/Ih4ckXUL9zXQZSOpCxRFkenBRDmIPs6TOIzT9FUuUYw==,iv:ScHGGMi6ASt4JW4q/KZK/W9+lXgD0COqSBxUMbkn+Bw=,tag:CtH29acZYvxNYJjMChdslg==,type:str]
    TELEGRAM_CHAT_ID: ENC[AES256_GCM,data:XSsv+yap/BOyng==,iv:XPXM6n+HcioTqQzbHI7d9f8+mkjNZJiCeVm/fWo7FGY=,tag:R58RddMyLny+93qqjBlYrA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPSXZ1a0NpVTJaMzJQT2tD
            QWtPUE4wcENqdmIyb2JFU3hMYVQvMVc3Y3lZCkRPYzVncXlRKy9SVUN4aUtWRzFG
            QitYYUo4dmV1NlFqRHdIUERsaElqQ2cKLS0tIEF1V09lbkY5MEdMSDBxbFJ1cDZi
            M2pIUnlvR2JCM0pBbG9vK3Q4VmJsbU0K12g4nsZ/LQ+jqq28WDzDH8cL63pQlSRh
            pmkdVWm/LOzerjQcacGHCgNpf1sbQYWY9PeN4OqRQqumG/M6vRxhFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1p4u42ltpqj0jxpuhx47pm0dhpmuqw2x8utyrxsr6xrgnzx0slq7q9u5jcw
    lastmodified: "2026-06-13T19:34:50Z"
    mac: ENC[AES256_GCM,data:VYXPUKkHsqjX4U1l5ZMx6Hk0FaVDBhsXPBeENORhv9ZSASUMGFaube59WyfC1RN8Qr/9fPjnYZ2odzUGeHpfyTPWkIVylD09R9yQ/dgG29yj8NUbwKxn2oLvBrD2PaDVOybwKvWJxJPFDcFt5ScsBHraOsVXjJZ6k95mXkkaDuk=,iv:L2WdHKBXbIY6PkEzrQ4vUcFGWXySwXSQDPn00vNzGmY=,tag:XByiXllhZ8lE1ogWh5uL1A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
