apiVersion: v2
name: platform-applications
description: "Apps of Apps — Central management of all platform applications"
type: application
version: 0.1.0
appVersion: "1.0"

keywords:
  - argocd
  - applications
  - platform
  - gitops

home: https://github.com/rprakashdass/homelab-gitops
sources:
  - https://github.com/rprakashdass/homelab-gitops

maintainers:
  - name: rprakashdass
    email: rprakashdass@gmail.com
